apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mario-che
resources:
  - namespace.yaml
  - privileged-sa.yaml
  - privileged-rb.yaml
  - privileged-sa-use-kata-policy.yaml
replacements:
  - source:
      kind: ServiceAccount
      name: privileged-sa
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterPolicy
          name: validate-privileged-sa
        fieldPaths:
          - spec.rules.[name=check-privileged-sa-use-kata].match.any.*.resources.namespaces.0
      - select:
          kind: RoleBinding
          name: system:openshift:scc:privileged
        fieldPaths:
          - subjects.[name=privileged-sa].namespace
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
