apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: run-priv-pod-using-kata
spec:
  admission: true
  background: false
  rules:
    - match:
        all:
          - resources:
              kinds:
                - Pod
              namespaces:
                - privpods
                - mario-project
      mutate:
        patchStrategicMerge:
          spec:
            +(runtimeClassName): kata
            serviceAccount: privsa
            serviceAccountName: privsa
      name: Run privilege pod using Kata containers runtime
      preconditions:
        any:
          - key: "{{request.object.spec.containers[?securityContext.privileged] | length(@)}}"
            operator: Equals
            value: 1
          - key: "{{request.object.spec.containers[?securityContext.runAsRoot] | length(@)}}"
            operator: Equals
            value: 1
          - key:
              "{{length(request.object.spec.containers[?securityContext.runAsUser ==
              `0`])}}"
            operator: Equals
            value: 1
      skipBackgroundRequests: true
  validationFailureAction: Audit
